# Generated by Django 5.2.6 on 2025-12-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_userprofile_allow_shared_lists_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Original recurring task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_frequency',
            field=models.CharField(choices=[('none', 'Does Not Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_interval',
            field=models.IntegerField(default=1, help_text='For custom frequency'),
        ),
    ]
