# Generated by Django 5.2.6 on 2025-12-09 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_achievement_userstats_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Write your note, memory, or idea here')),
                ('category', models.CharField(choices=[('personal', '👤 Personal'), ('ideas', '💡 Ideas'), ('dates', '📅 Important Dates'), ('quotes', '💬 Quotes'), ('reference', '📚 Reference'), ('other', '🔖 Other')], default='personal', max_length=20)),
                ('color', models.CharField(choices=[('#FFD700', '🟡 Yellow'), ('#FF69B4', '🔴 Pink'), ('#87CEEB', '🔵 Blue'), ('#98FB98', '🟢 Green'), ('#DDA0DD', '🟣 Purple'), ('#FFB6C1', '🟠 Coral')], default='#FFD700', max_length=7)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top')),
                ('is_archived', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created'],
            },
        ),
    ]
