# Generated by Django 5.2.6 on 2025-12-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='alarm_snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='alarm_time',
            field=models.DateTimeField(blank=True, help_text='When to trigger alarm', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='alarm_tone',
            field=models.CharField(default='default', help_text='Alarm sound file', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alarm_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alarm_minutes_before',
            field=models.IntegerField(default=0, help_text='Minutes before due date to alarm'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_alarm_tone',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
